@startuml Network
!define AzurePuml https://raw.githubusercontent.com/plantuml-stdlib/Azure-PlantUML/release/2-2/dist
!includeurl AzurePuml/AzureCommon.puml
!includeurl AzurePuml/Networking/all.puml
!includeurl AzurePuml/Compute/AzureVirtualMachine.puml



AzureVirtualNetwork(code, "code", "2") {
    AzureVirtualMachine(router1, "Router-1", "D32s_v5")
    AzureVirtualMachine(router2, "Router-2", "D32s_v5")
}




@enduml